services:

  # zeiterfassung:
  #   image: registry.example.com/path/example/zeiterfassung:2.7.0-SNAPSHOT
  #   network_mode: "host"
  #   environment:
  #     SERVER_PORT: 8080
  #     # Database
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/zeiterfassung
  #     SPRING_DATASOURCE_USERNAME: admin_user
  #     SPRING_DATASOURCE_PASSWORD: admin_password
  #     # Mail
  #     ZEITERFASSUNG_MAIL_FROM: zeiterfassung@example.org
  #     ZEITERFASSUNG_MAIL_FROMDISPLAYNAME: zeiterfassung
  #     ZEITERFASSUNG_MAIL_REPLYTO: replyto@example.org
  #     ZEITERFASSUNG_MAIL_REPLYTODISPLAYNAME: replyto
  #     SPRING_MAIL_HOST: localhost
  #     SPRING_MAIL_PORT: 1025
  #     # OpenID Connect identity provider
  #     SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-ID: zeiterfassung
  #     SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-SECRET: zeiterfassung-secret
  #     SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-NAME: zeiterfassung
  #     SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_PROVIDER: default
  #     SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_SCOPE: openid,profile,email,roles
  #     SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_AUTHORIZATION-GRANT-TYPE: authorization_code
  #     SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_REDIRECT-URI: http://{baseHost}:8080/login/oauth2/code/{registrationId}
  #     SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_DEFAULT_ISSUER-URI: https://keycloak.omveon.com/realms/zeiterfassung-realm
  #     # SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_DEFAULT_ISSUER-URI: http://localhost:8090/realms/zeiterfassung-realm
  #     ZEITERFASSUNG_SECURITY_OIDC_SERVER-URL: https://keycloak.omveon.com
  #     # ZEITERFASSUNG_SECURITY_OIDC_SERVER-URL: http://localhost:8090
  #     ZEITERFASSUNG_SECURITY_OIDC_LOGIN-FORM-URL: http://localhost:8080/oauth2/authorization/default
  #     SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  #   depends_on:
  #     keycloak:
  #       condition: service_started
  #     postgres:
  #       condition: service_healthy
  #     mailhog:
  #       condition: service_started

  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: zeiterfassung
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password
      POSTGRES_APP_USER: app_user
      POSTGRES_APP_PASSWORD: app_password
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 3s
      timeout: 1s
      retries: 5
    volumes:
        - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
        - '1025:1025'
        - '8025:8025'
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: '8090'
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_CACHE: 'local'
    ports:
      - '8090:8090'
    volumes:
      - ./docker/keycloak/export:/opt/keycloak/data/import

